name: 'buildcache-action'
description: 'GitHub Action that installs and configures buildcache to accelerate compilation'
author: 'Mike Hardy'
inputs:
  key:
    description: 'An additional key for the cache'
    required: false
  access_token:
    required: false
    description: 'Your GitHub Access Token to fetch buildcache latest build, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
  configfile:
    required: false
    description: 'path to buildcache config file - https://github.com/mbitsnbites/buildcache/blob/master/doc/configuration.md'
    default: 'buildcache will rely on default config file or if missing, default values for all settings'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
