name: 'buildcache-action'
description: 'GitHub Action that installs and configures buildcache to accelerate compilation'
author: 'Mike Hardy'
inputs:
  key:
    description: 'An additional string to use in the cache key'
    required: false
  access_token:
    required: false
    description: 'Your GitHub Access Token to fetch buildcache latest build, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
  upload_buildcache_log:
    required: false
    default: false
    description: 'If set to true, any buildcache log create during the run will be uploaded as an artifact'
  zero_buildcache_stats:
    required: false
    default: true
    description: 'Defaults to true, will print stats on restore, then zero them for run-specific stats on save'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
